<?php

/**
 * Cities of Morocco
 * - 1472 Cities
 * 
 * Source: 
 * - https://fr.wikipedia.org/wiki/Regions_du_Maroc
 *
 * @author  Anas Ait Khali <aitkhali.anas@outlook.com> | https://lehealthystore.ma
 * @version 1.0.0
 * @license http://www.gnu.org/licenses/gpl-2.0.html
 */

global $places;

$places['MA'] = array(
		// TANGER-TETOUAN-AL HOCEIMA
	'01' => array(
		    'AIN BEIDA'
        'AIN BENABBOU'
'AIN DORIJ'
'AIT KAMRA'
'AIT YOUSSEF OU ALI'
'AL HOCEIMA'
'AL AOUAMRA'
'AMTAR'
'ARBAA AYACHA'
'ARBAA TAOURIRT'
'ASIFANE'
'ASSILAH'
'ASJEN'
'ASMATEN'
'AZLA'
'BAB BERRET'
'BAB TAZA'
'BAHRAOUIYNE TANJA'
'BAHRIYNE EL AOUAMA'
'BENI BOUZRA'
'BENI GMIL MESTASSA'
'BENI RZEN'
'BENI SELMANE'
'BENI YDER'
'BGHAGHZA'
'BNI ABDALLAH'
'BNI AHMED'
'BNI AHMED GHARBIA'
'BNI AMMART'
'BNI BCHIR'
'BNI BOUAYACH'
'BNI BOUFRAH'
'BNI BOUNSAR'
'BNI HADIFA'
'BNI KARRICH FOUKI'
'BNI QUOLLA'
'BNI SMIH'
'BRIKCHA'
'CHAKRANE'
'CHEFCHAOUEN'
'DAR BEN SADDOUK'
'DAR CHAOUI'
'DERDERA'
'DERKOUL'
'EL BORCH'
'EL FENDEQ'
'EL MELHA'
'FIFI'
'FNIDQ'
'GZENAYA'
'HAD RHARBIA'
'HAD RHDIR KROUCH'
'HAJR ENHAL'
'HAKKAMA'
'IKAOUEN'
'IMZOUREN'
'IOUANE'
'ISSAGUEN'
'IZEMMOUREN'
'JEBHA'
'JEMAA EL OUED'
'KAA ASRASS'
'KETAMA'
'KHEMIS SAHEL'
'KSAR EL KEBIR'
'KSAR SGHIR'
'LARACHE'
'Mansoura'
'MARTIL'
'MDIQ'
'MECHERAH'
'MELLOUSSA'
'MOKRISSET'
'MOULAY ABDESSLAM'
'NEKKOUR'
'OUAOUZGANE'
'OUED LAOU'
'OUEZZANE'
'OUNNANA'
'RISSANA JANOUBIA'
'SANIA EL JADIDA'
'SEBT BNI GARFET'
'SEBT RMEL'
'SEBT ZENIATE'
'SIDI AHMED CHERIF'
'SIDI BOUSBER'
'SIDI BOUZINEB'
'SIDI REDOUANE'
'SOUK TOLBA'
'STEHA'
'TABARANNT'
'Taghzout'
'TALEMBOTE'
'TAMOROTE'
'TANACOB'
'Tanger - Al aouama'
'Tanger - Bni Makada'
'Tanger - Boukhalf'
'Tanger - Branss'
'Tanger - Centre ville'
'Tanger - Comp hassani'
'Tanger - Dradeb'
'Tanger - Gzenaya'
'Tanger - Iberia'
'Tanger - Malabata'
'Tanger - Messnana'
'Tanger - Mghogha'
'Tanger - Sidi driss'
'TARGUIST'
'TARHREMT'
'TASSIFT'
'TATOUFET'
'TEROUAL'
'TETOUAN'
'TIZI TCHEN'
'TLATA ASSIFANE'
'TLATA RISSANA'
'TNINE SIDI EL YAMANI'
'TORRES DE ALCALA'
'ZAAROURA'
'ZAOUIA SIDI KACEM'
'ZOCO JEMIS DE ANYERA'
'ZOUADA'
'ZOUMI'
	),

// Use this filter to handle the Cities of Morocco
$places['MA'] = apply_filters('scpwoo_custom_places_ma', $places['MA']);
